{% set name = "libaio" %}
{% set version = "0.9.4" %}

package:
  name: python-{{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eebaf2356ffbd8dac9fa0e1931b32f53d4271a8be8416c06a201747a2f7cc2c3


build:
  # the python package is noarch, but requires an a linux only package.
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - libaio

test:
  requires:
    - python {{ python_min }}
  imports:
    - libaio
  commands:
    - python -m libaio.test -vv

about:
  home: https://github.com/vpelletier/python-libaio
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Python wrapper for libaio
  description: |
    Linux AIO API wrapper

    This is about in-kernel, file-descriptor-based asynchronous I/O. It has
    nothing to do with the asyncio standard module.

extra:
  recipe-maintainers:
    - hmaarrfk
