{% set version = "0.9.5" %}

package:
  name: python-libaio
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/libaio/libaio-{{ version }}.tar.gz
  sha256: 5f674b21a63389308eaf76f5fa2227cadc63d739295dc75d295cfc55c521228a
  patches:
    - fix_error_handling_for_missing_so_file.patch

build:
  # the python package is noarch, but requires an a linux only package.
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - libaio

test:
  requires:
    - python {{ python_min }}
  imports:
    - libaio
  commands:
    - python -m libaio.test -vv

about:
  home: https://github.com/vpelletier/python-libaio
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  summary: Python wrapper for libaio
  description: |
    Linux AIO API wrapper

    This is about in-kernel, file-descriptor-based asynchronous I/O. It has
    nothing to do with the asyncio standard module.

extra:
  recipe-maintainers:
    - hmaarrfk
